apiVersion: v1
kind: deployment
metadata:
  namespace: freight-fox
  name: f-fox-document-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f-fox-document-storage
    template:
      metadata:
        labels:
          app: f-fox-document-storage
      spec:
        containers:
          - name: f-fox-document-storage
            image: "Dummy-Image"
            ports:
             - containerPort: 8080
            env:
              - name: SERVER_PORT
                value: "8080"
              - name: S3_BUCKET_NAME
                value: "freight-fox-doc-storage"
              - name: AWS_REGION
                value: "ap-south-1"
              - name: AWS_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: f-fox-document-storage-secret
                    key: AWS_ACCESS_KEY
              - name: AWS_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: f-fox-document-storage-secret
                    key: AWS_SECRET_KEY
            resources:
              request:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
            livelinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 60
              periodSeconds: 30







